name: Build and Deploy to Azure

on:
  push:
    branches:
      - master  # Déclenche le workflow sur un push sur la branche principale
  pull_request:
    branches:
      - master  # Déclenche aussi sur une PR vers la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: projetcloud.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t projetcloud.azurecr.io/myapp:latest
          docker push projetcloud.azurecr.io/myapp:latest

      - name: Initialize Terraform
        env:
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          az login
          terraform init
          terraform apply
        
   
