name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also trigger on PR to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 3: Build and push Docker image to ACR
      - name: Build and Push Docker image to ACR
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest

      # Step 4: Log in to Azure using Azure CLI (Interactive authentication)
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}       # (Optional if using Azure CLI)
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Your Azure subscription ID

      # Step 5: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 6: Apply Terraform configuration to deploy the app
      - name: Apply Terraform Configuration
        run: terraform apply
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
   
